export const CLASSNAME__ROOT = 'thumbnail-carousel';
export const CLASSNAME__BUTTON = `${CLASSNAME__ROOT}-button`;
export const CLASSNAME__ITEM_VIEWER = 'item-viewer';
export const CLASSNAME__ITEM_VIEWER_BUTTON = `${CLASSNAME__ITEM_VIEWER}-button`;
export const CLASSNAME__OVERLAY_BUTTON_TOP = `${CLASSNAME__ROOT}-video-overlay-custom-button-top`;
export const CLASSNAME__OVERLAY_BUTTON_RIGHT = `${CLASSNAME__ROOT}-video-overlay-custom-button-right`;
export const MOBILE_PIXEL_WIDTH = 655;
export const EMPTY_STRING = "";
export const VIDEO_EXTENSIONS = ["mp4", "ogv", "webm", "ogg"];