export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const CLICK_SKILL = 'CLICK_SKILL';
export const ADD_REPO = 'ADD_REPO';
export const SET_IS_ANIMATING = 'SET_IS_ANIMATING';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_SECTIONS_TO_SKIP_ANIMATION = 'SET_SECTIONS_TO_SKIP_ANIMATION';
export const SET_PREVIOUS_URL = 'SET_PREVIOUS_URL';



