export const PAGE_NAV_LAYOUT_LINK_FILL = 0.15;
export const PAGE_NAV_LAYOUT_LINK_ON_HOVER_FILL = 0.5;
export const PAGE_NAV_LAYOUT_LINK_TEXT_BACKGROUND_COLOR_OPACITY = 0.1;
export const PAGE_NAV_LAYOUT_LINK_TEXT_COLOR_OPACITY = 0.875;
