export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const CLICK_SKILL = 'CLICK_SKILL';
export const ADD_REPO = 'ADD_REPO';
export const SET_IS_ANIMATING = 'SET_IS_ANIMATING';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_VIEW_PORT_WIDTH = 'SET_VIEW_PORT_WIDTH';
export const SET_SECTIONS_TO_SKIP_ANIMATION = 'SET_SECTIONS_TO_SKIP_ANIMATION';
export const SET_PREVIOUS_URL = 'SET_PREVIOUS_URL';
export const SET_SCROLL_PERCENT = 'SET_SCROLL_PERCENT';
export const SET_SOUNDS = 'SET_SOUNDS';
export const SET_CLICKED_BRIDGE_INFO_BUTTON_COUNT = 'SET_CLICKED_BRIDGE_INFO_BUTTON_COUNT';
export const SET_CURRENT_BRIDGE_SECTION = 'SET_CURRENT_BRIDGE_SECTION';
export const SET_BRIDGE_SECTIONS = 'SET_BRIDGE_SECTIONS';
export const SET_HEADER_HEIGHT = 'SET_HEADER_HEIGHT';
export const SET_LAST_SECOND_ROW_CARD_NUMBER = 'SET_LAST_SECOND_ROW_CARD_NUMBER';
export const SET_BRIDGE_CARDS = 'SET_BRIDGE_CARDS';
export const SET_HAS_CLICKED_A_LINK = 'SET_HAS_CLICKED_A_LINK';







